Repository pagopa/pagopa-payment-options-service, pull requests merged in 2024-10, with the labels that each got.

#12 [PPANTT-131] feat: add introducing integration tests
  .github/workflows/code_review.yml
  docker/alertmanager/alertmanager.conf
  docker/docker-compose.yml
  docker/grafana/grafana_config.ini
  docker/grafana/grafana_datasources.yml
  docker/otel-collector/otel-collector-config.yaml
  docker/prometheus/alert_rules.yml
  docker/prometheus/prometheus.yml
  docker/run_docker.sh
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  integration-test/README.md
  integration-test/run_integration_test.sh
  integration-test/src/README.md
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.local
  integration-test/src/config/.env.uat
  integration-test/src/features/get_payment_options.feature
  integration-test/src/package.json
  integration-test/src/step_definitions/payment_options_step.js
  integration-test/src/step_definitions/support/client/payment_options_client.js
  integration-test/src/step_definitions/support/utility/axios_common.js
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/options/clients/CreditorInstitutionRestClient.java
  src/main/java/it/gov/pagopa/payment/options/clients/CreditorInstitutionRestClientInterface.java
  src/main/java/it/gov/pagopa/payment/options/models/clients/cache/Station.java
  src/main/java/it/gov/pagopa/payment/options/services/CreditorInstitutionService.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/options/clients/CreditorInstitutionRestClientTest.java
  src/test/java/it/gov/pagopa/payment/options/test/extensions/WireMockExtensions.java
Labels: size/large, skip

#14 Update for UAT release
  .identity/env/uat/backend.tfvars
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/resources/application.properties
Labels: size/small, patch

#9 [PPANTT-73] feat: Performance tests
  .devops/performance-test-pipelines.yaml
  .devops/performance-test-pipelines.yml
  perfomance-test/README.md
  performance-test/README.md
  performance-test/docker-compose.yaml
  performance-test/nginx/nginx.conf
  performance-test/run_performance_test.sh
  performance-test/src/dev.environment.json
  performance-test/src/local.environment.json
  performance-test/src/modules/payment_options_client.js
  performance-test/src/package.json
  performance-test/src/payment_options_service_test.js
  performance-test/src/test-types/constant.json
  performance-test/src/test-types/load.json
  performance-test/src/test-types/spike.json
  performance-test/src/test-types/stress.json
  performance-test/src/uat.environment.json
Labels: size/large, skip

#15 feat: update openapi
  openapi/openapi.json
  src/main/java/it/gov/pagopa/payment/options/resources/PaymentOptionsResource.java
Labels: size/small, patch

#16 fix: Add NOTICE_TYPE env to docker compose and script
  .devops/performance-test-pipelines.yml
  performance-test/docker-compose.yaml
  performance-test/run_performance_test.sh
Labels: size/small, skip

#17 feat: Updated openapi.json, PaymentOptionsResource
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/options/App.java
  src/main/java/it/gov/pagopa/payment/options/models/enums/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/payment/options/resources/PaymentOptionsResource.java
Labels: size/small, patch
