Repository pagopa/pagopa-payment-options-service, pull requests merged in 2024-12, with the labels that each got.

#25 [PPANTT-212] feat: Bump chart version to 7.1.1
  .github/workflows/deploy_with_github_runner.yml
  .identity/00_data.tf
  .identity/01_github_environment.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: minor, size/small

#22 feat: Test new runner
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
Labels: size/small, patch

#28 fix: deploy GHA
  .github/workflows/deploy_with_github_runner.yml
Labels: size/small, skip

#30 feat: Updated policy
  infra/policy/_get_payment_options_policy.xml
Labels: size/small, skip

#31 fix: Increase memory and add java option
  helm/values-prod.yaml
Labels: size/small, patch

#29 fix: Update performance test
  .identity/00_data.tf
  .identity/01_github_environment.tf
  integration-test/src/config/.env.dev
  integration-test/src/config/.env.uat
  performance-test/src/dev.environment.json
  performance-test/src/modules/payment_options_client.js
  performance-test/src/payment_options_service_test.js
  performance-test/src/uat.environment.json
Labels: size/small, skip

#32 fix: Policy
  infra/policy/_get_payment_options_policy.xml
Labels: size/small, skip
