Repository pagopa/pagopa-payment-options-service, pull requests merged in 2024-09, with the labels that each got.

#4 [PPANTT-80] feat: add psp api
  README.md
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/99_main.tf
  infra/99_variables.tf
  infra/env/itn-dev/backend.ini
  infra/env/itn-dev/backend.tfvars
  infra/env/itn-dev/terraform.tfvars
  infra/env/itn-prod/backend.ini
  infra/env/itn-prod/backend.tfvars
  infra/env/itn-prod/terraform.tfvars
  infra/env/itn-uat/backend.ini
  infra/env/itn-uat/backend.tfvars
  infra/env/itn-uat/terraform.tfvars
  infra/policy/_base_policy.xml
  infra/terraform.sh
  openapi/generate_openapi.sh
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/options/App.java
  src/main/java/it/gov/pagopa/payment/options/clients/CreditorInstitutionRestClient.java
  src/main/java/it/gov/pagopa/payment/options/clients/CreditorInstitutionRestClientInterface.java
  src/main/java/it/gov/pagopa/payment/options/models/clients/cache/BrokerPsp.java
  src/main/java/it/gov/pagopa/payment/options/models/clients/cache/ConfigDataV1.java
  src/main/java/it/gov/pagopa/payment/options/models/clients/cache/PaymentServiceProvider.java
  src/main/java/it/gov/pagopa/payment/options/models/enums/AppErrorCodeEnum.java
  src/main/java/it/gov/pagopa/payment/options/resources/PaymentOptionsResource.java
  src/main/java/it/gov/pagopa/payment/options/services/CreditorInstitutionService.java
  src/main/java/it/gov/pagopa/payment/options/services/PaymentOptionsService.java
  src/test/java/it/gov/pagopa/payment/options/OpenApiGenerationTest.java
  src/test/java/it/gov/pagopa/payment/options/resources/PaymentOptionsResourceTest.java
  src/test/java/it/gov/pagopa/payment/options/services/PaymentOptionsServiceTest.java
Labels: enhancement, minor, size/large

#2 [PPANTT-77] feat: Added and configured create dashboard opex action
  .gitignore
  .opex/env/prod/backend.tfvars
  .opex/env/prod/config.yaml
  .opex/env/prod/terraform.tfvars
Labels: size/small, skip

#5 [PPANTT-90] feat: add result event producers
  .github/workflows/code_review.yml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/options/App.java
  src/main/java/it/gov/pagopa/payment/options/clients/CreditorInstitutionRestClient.java
  src/main/java/it/gov/pagopa/payment/options/exception/PaymentOptionsException.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/Body.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/CategoriaEvento.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/Esito.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/OdpVerifyRe.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/Properties.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/SottoTipoEvento.java
  src/main/java/it/gov/pagopa/payment/options/models/events/verifyKo/Creditor.java
  src/main/java/it/gov/pagopa/payment/options/models/events/verifyKo/DebtorPosition.java
  src/main/java/it/gov/pagopa/payment/options/models/events/verifyKo/FaultBean.java
  src/main/java/it/gov/pagopa/payment/options/models/events/verifyKo/Psp.java
  src/main/java/it/gov/pagopa/payment/options/models/events/verifyKo/VerifyEventKo.java
  src/main/java/it/gov/pagopa/payment/options/resources/PaymentOptionsResource.java
  src/main/java/it/gov/pagopa/payment/options/services/ConfigCacheService.java
  src/main/java/it/gov/pagopa/payment/options/services/CreditorInstitutionService.java
  src/main/java/it/gov/pagopa/payment/options/services/EventService.java
  src/main/java/it/gov/pagopa/payment/options/services/PaymentOptionsService.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/options/PaymentOptionsExtendedTest.java
  src/test/java/it/gov/pagopa/payment/options/WireMockExtensions.java
  src/test/java/it/gov/pagopa/payment/options/clients/CreditorInstitutionRestClientTest.java
  src/test/java/it/gov/pagopa/payment/options/resources/PaymentOptionsResourceTest.java
  src/test/java/it/gov/pagopa/payment/options/services/EventServiceTest.java
  src/test/java/it/gov/pagopa/payment/options/services/PaymentOptionsServiceTest.java
  src/test/java/it/gov/pagopa/payment/options/test/extensions/KafkaTestResourceLifecycleManager.java
  src/test/java/it/gov/pagopa/payment/options/test/extensions/WireMockExtensions.java
Labels: enhancement, minor, size/large

#6 [PPANTT-132] feat: add authorizer policy
  infra/04_apim_api.tf
  infra/policy/_base_policy.xml
  infra/policy/_get_payment_options_policy.xml
  src/main/java/it/gov/pagopa/payment/options/exception/mapper/ExceptionMapper.java
  src/main/java/it/gov/pagopa/payment/options/resources/PaymentOptionsResource.java
  src/main/java/it/gov/pagopa/payment/options/services/EventService.java
  src/main/java/it/gov/pagopa/payment/options/services/PaymentOptionsService.java
Labels: enhancement, size/small, skip

#7 [PPANTT-83] feat: update log format to ecs
  .github/workflows/code_review.yml
  .github/workflows/create_dashboard.yaml
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/integration_test.yml
  .identity/99_variables.tf
  .identity/env/dev/backend.tfvars
  .identity/env/dev/terraform.tfvars
  .identity/env/prod/backend.tfvars
  .identity/env/prod/terraform.tfvars
  .identity/env/uat/backend.tfvars
  .identity/env/uat/terraform.tfvars
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
  src/main/resources/application.properties
Labels: enhancement, size/small, patch

#10 feat: updated helm values
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  src/main/resources/application.properties
Labels: enhancement, size/small, skip

#11 fix: updated helm keyvault name
  .github/workflows/deploy_with_github_runner.yml
  Dockerfile
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/env/itn-dev/terraform.tfvars
  infra/env/itn-prod/terraform.tfvars
  infra/env/itn-uat/terraform.tfvars
  infra/policy/_get_payment_options_policy.xml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/Body.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/Esito.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/EventType.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/OdpVerifyRe.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/Properties.java
  src/main/java/it/gov/pagopa/payment/options/models/events/odpRe/Status.java
  src/main/java/it/gov/pagopa/payment/options/resources/PaymentOptionsResource.java
  src/main/java/it/gov/pagopa/payment/options/services/ConfigCacheService.java
  src/main/java/it/gov/pagopa/payment/options/services/EventService.java
  src/main/java/it/gov/pagopa/payment/options/services/PaymentOptionsService.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/payment/options/services/EventServiceTest.java
Labels: size/large, patch

#8 [PPANTT-135] chore: defined re schema
  templates/payment-options-re.json
Labels: size/small, skip
